# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- none

pool:
  vmImage: ubuntu-latest

steps:
- task: JFrogGradle@1
  inputs:
    gradleBuildFile: 'build.gradle'
    tasks: 'artifactoryPublish'
    artifactoryResolverService: 'art'
    sourceRepo: 'gradle-virtual'
    artifactoryDeployerService: 'art'
    targetRepo: 'gradle-dev-local'
    useWrapper: true
    deployIvyDesc: false
    collectBuildInfo: true
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    includeEnvVars: true

- task: JFrogPublishBuildInfo@1
  inputs:
    artifactoryConnection: 'art'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'